baseURL = 'https://seanbintley.co.uk/'
languageCode = 'en-gb'
title = 'Sean Bintley'
theme = 'hugo-brewm'
[privacy]
    [privacy.youTube]
        disable = false
        privacyEnhanced = true
[params]
    [params.comments]
        disabled = true
    [params.home]
        disableSlide = true
        disableListing = true
    [params.logo]
        logoType = true